### ISSUE TITLE
vendor usb

### ISSUE THREAD

**Issue by Docfch** [czietz/picowifi#2]
### What happened?

Hello,
How can i use the vendor as host ?
Thanks.

### Firmware version

last

### Software versions on the Atari

USB drivers: ....
uIP tool: ....
STinG driver: ....
MiNT driver: ....

### Hardware

pico w

**Comment by czietz** [comment]
Sorry, can you please elaborate your question more? What are you trying to achieve with the PicoWifi? Also please provide the software versions you are using on the Atari side.

**Comment by Docfch** [comment]
thanks for the reply.
I have three hubs, each with an STM32, and I want to connect a PicoW to each to communicate via WiFi (see image above) and adapt it with the PicoWifi code. 
The USB of the PicoW should work as a vendor host. And my question is : how can i implement the usb vendor host in the code ? (Now the PicoWifi uses usb vendor device)

![image](https://github.com/czietz/picowifi/assets/84841796/64219af5-4e54-497f-a947-a06fd9b48327)

**Comment by czietz** [comment]
I’m afraid this is outside of the scope of this project. The goal of the PicoWifi is to provide easy Wifi connectivity to Atari computers; for which the PicoWifi must operate in *device* mode, not in host mode.

I suggest you ask your question in the Raspberry Pi Pico forums instead: https://forums.raspberrypi.com/viewforum.php?f=143

PS: If I may add: Opening an issue in a project to ask general questions (unrelated to the project) is not the adequate way to get your questions answered.
