### ISSUE TITLE
Can't get picowifi to work with latest freemint bootable builds

### ISSUE THREAD

**Issue by fdanapfel** [czietz/picowifi#4]
### What happened?

When trying to set up a network connection using the picowifi attached to a Lighning VME USB interface on an Atari TT030 using the latest bootable build from https://tho-otto.de/snapshots/freemint/bootable/ I get the following error:
```
# ifconfig piw0 addr <ipaddr> up
piw0: cannot get FLAGS: No such file or directory
```

I've renamed the picowifi.xix in the c:/mint/1-19-040b/ directory to picowifi.xif and also removed the comment signs from the line in mint.cnf to enable the loading of the USB modules. These are the only changes I did to the mint setup provided by the bootable build.

I can see that the USB modules are loaded when mint is booting and accessing a USB stick attached to the USB port from TeraDesk works without issue. Also the picowifi works without issues under TOS with UIP-USB.TOS when using the USB drivers from https://tho-otto.de/snapshots/freemint/usb4tos/

Therefore I'm guessing there is something wrong in the freemint bootable build that prevents the picowifi.xif from being loaded.

### Firmware version

The one that was available under "Releases" before the current one

### Software versions on the Atari

USB drivers: the ones included in latest freemint bootable build ([freemint-latest-02060-tt_falcon_clones.zip](https://tho-otto.de/snapshots/freemint/bootable/freemint-latest-02060-tt_falcon_clones.zip))
uIP tool: ....
STinG driver: ....
MiNT driver: picowifi.xif included in latest freemint bootable build ([freemint-latest-02060-tt_falcon_clones.zip](https://tho-otto.de/snapshots/freemint/bootable/freemint-latest-02060-tt_falcon_clones.zip))

### Hardware

Lightning VME in Atari TT030.

**Comment by czietz** [comment]
> ```
> # ifconfig piw0 addr <ipaddr> up
> piw0: cannot get FLAGS: No such file or directory
>```

Note that the device is called p**wi**0, not piw0.

**Comment by fdanapfel** [comment]
OOOOPS, completely missed that typo (guess I've done too much Raspberry Pi related stuff lately) :-(

Thanks for pointing this out and also for the quick response.

And also a big THANKS for creating picowifi 🥇
